module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  config: 0
  config_devel: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  datetime: 0
  dblog: 0
  ddd_attendees: 0
  ddd_fixtures: 0
  ddd_global: 0
  ddd_map: 0
  ddd_sessions: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference: 0
  entity_reference_revisions: 0
  eu_cookie_compliance: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  image: 0
  link: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  path: 0
  rdf: 0
  recaptcha: 0
  rest: 0
  restui: 0
  serialization: 0
  statistics: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  ddd: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  ddd2016: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
