<?php

/**
 * @file
 * Contains ddd_attendees.module..
 */

/**
 * Implements hook_theme().
 */
function ddd_attendees_theme($existing, $type, $theme, $path) {
  return [
    'ddd_attendees_view' => [
      'template' => 'ddd_attendees_view',
      'variables' => ['attendees' => []],
    ],
    'ddd_individual_sponsors_view' => [
      'template' => 'ddd_individual_sponsors_view',
      'variables' => ['individual_sponsors' => []],
    ],
  ];
}
